### ISSUE TITLE
Fix crash reported in TestFairy

### ISSUE THREAD

**Issue by atsakiridis** [Mobicents/restcomm-android-sdk#119]
java.lang.RuntimeException: Unable to resume activity {com.telestax.restcomm_messenger/com.telestax.restcomm_messenger.MainActivity}: java.lang.NullPointerException: null arg address
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2987)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3016)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1419)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5434)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:834)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException: null arg address
	at android.gov.nist.javax.sip.header.HeaderFactoryImpl.createContactHeader(HeaderFactoryImpl.java:299)
	at org.mobicents.restcomm.android.sipua.impl.sipmessages.Register.MakeRequest(Register.java:53)
	at org.mobicents.restcomm.android.sipua.impl.SipManager.Register(SipManager.java:297)
	at org.mobicents.restcomm.android.sipua.impl.DeviceImpl.Register(DeviceImpl.java:184)
	at org.mobicents.restcomm.android.client.sdk.RCDevice.updateParams(RCDevice.java:370)
	at com.telestax.restcomm_messenger.MainActivity.initializeSipFromPreferences(MainActivity.java:239)
	at com.telestax.restcomm_messenger.MainActivity.onResume(MainActivity.java:269)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1255)
	at android.app.Activity.performResume(Activity.java:5199)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2974)
	... 10 moreAdd messages in separate screen

**Comment by atsakiridis** [comment]
Finally reproduced this. Here's the scenario:
- Start messenger without network (everything is fine, we get the 'no network connectivity' message)
- Enable Wifi and try to register (messenger crashes)
Seems to be that since local ip wasn't set properly during initialization (since there was no network connectivity) and wasn't updated when we went online now we get the error

Proper solution is to implement reachability

**Comment by atsakiridis** [comment]
Fixed with 5c206e6b70e60289b4302d55b435909ae15c02ff
