### ISSUE TITLE
Messenger crash when testing on a device without front camera

### ISSUE THREAD

**Issue by atsakiridis** [Mobicents/restcomm-android-sdk#154]
This happened when testing with Desi. She tried to make a video call in a device without camera. She got an error 3 times and then the app crashed:

android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@41affd10 is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:720)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:356)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:234)
	at android.view.WindowManagerImpl$CompatModeWrapper.addView(WindowManagerImpl.java:153)
	at android.view.Window$LocalWindowManager.addView(Window.java:559)
	at android.app.Dialog.show(Dialog.java:301)
	at com.telestax.restcomm_messenger.CallActivity.showOkAlert(CallActivity.java:379)
	at com.telestax.restcomm_messenger.CallActivity.onDisconnected(CallActivity.java:300)
	at org.mobicents.restcomm.android.client.sdk.RCConnection$14.run(RCConnection.java:790)
	at android.os.Handler.handleCallback(Handler.java:615)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:177)
	at android.app.ActivityThread.main(ActivityThread.java:4947)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by atsakiridis** [comment]
After inspecting the TestFairy session this doesn't seem related to the lack of front camera. Seems that an Android Alert window was requested in an activity that wasn't in the foreground. While Messenger was in the messages screen, it seems that we got a late failed disconnect from a previous call (i.e. onDisconnected). As a result, since CallActivity wasn't active, we got the crash
