### ISSUE TITLE
Crash during activity destruction

### ISSUE THREAD

**Issue by atsakiridis** [Mobicents/restcomm-android-sdk#163]
Seems like the Restcomm Client facilities have already been destroyed when Activity onDestroy() is called and a missing check in the size of the RCDevice array causes this:

java.lang.RuntimeException: Unable to destroy activity {com.telestax.restcomm_messenger/com.telestax.restcomm_messenger.MainActivity}: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3497)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3515)
	at android.app.ActivityThread.access$1400(ActivityThread.java:135)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1249)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5021)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.get(ArrayList.java:308)
	at org.mobicents.restcomm.android.client.sdk.RCClient.shutdown(RCClient.java:111)
	at com.telestax.restcomm_messenger.MainActivity.onDestroy(MainActivity.java:149)
	at android.app.Activity.performDestroy(Activity.java:5403)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1120)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3484)
	... 11 more

**Comment by atsakiridis** [comment]
Fixed this by guarding against improper array access, but also did some improvements in how RCClient & RCDevice instances are managed
