### ISSUE TITLE
Fix NPE on onSharedPreferenceChanged

### ISSUE THREAD

**Issue by atsakiridis** [Mobicents/restcomm-android-sdk#166]
This was reported by TestFairy. My guess is that RCDevice had been somehow deallocated when this notification comes, hence the crash. 

Reported with: Messenger 1.0.0-BETA2#2

java.lang.NullPointerException
	at com.telestax.restcomm_messenger.MainActivity.onSharedPreferenceChanged(MainActivity.java:297)
	at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:475)
	at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:385)
	at android.preference.Preference.tryCommit(Preference.java:1372)
	at android.preference.Preference.persistString(Preference.java:1405)
	at android.preference.EditTextPreference.setText(EditTextPreference.java:88)
	at android.preference.EditTextPreference.onDialogClosed(EditTextPreference.java:142)
	at android.preference.DialogPreference.onDismiss(DialogPreference.java:383)
	at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1238)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5021)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by atsakiridis** [comment]
Finally reproduced this. Scenario:

- Open Messenger with Wifi enabled
- Press Android Back (not Home) so that Main Activity is destroyed and we are navigated to home screen
- Open Messenger again
- Open Settings and change username and press ok (Crash occurs)

Stack trace with Messenger 1.0.0-BETA2#8:

09-04 15:48:49.826  24651-24651/com.telestax.restcomm_messenger E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.telestax.restcomm_messenger, PID: 24651
    java.lang.NullPointerException
            at com.telestax.restcomm_messenger.MainActivity.onSharedPreferenceChanged(MainActivity.java:289)
            at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:475)
            at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:385)
            at android.preference.Preference.tryCommit(Preference.java:1380)
            at android.preference.Preference.persistString(Preference.java:1413)
            at android.preference.EditTextPreference.setText(EditTextPreference.java:88)
            at android.preference.EditTextPreference.onDialogClosed(EditTextPreference.java:142)
            at android.preference.DialogPreference.onDismiss(DialogPreference.java:390)
            at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1238)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5146)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
            at dalvik.system.NativeStart.main(Native Method)
