### ISSUE TITLE
NPE at android.gov.nist.javax.sip.SipStackImpl.deleteListeningPoint

### ISSUE THREAD

**Issue by atsakiridis** [Mobicents/restcomm-android-sdk#167]
This might have been fixed already with the latest changes I did in the registrations, but let's keep it around for better tracking

Reported with: Messenger 1.0.0-BETA2#2

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.telestax.restcomm_messenger/com.telestax.restcomm_messenger.SettingsActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
	at android.app.ActivityThread.access$800(ActivityThread.java:135)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5021)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at android.gov.nist.javax.sip.stack.UDPMessageProcessor.stop(UDPMessageProcessor.java:270)
	at android.gov.nist.javax.sip.stack.SIPTransactionStack.removeMessageProcessor(SIPTransactionStack.java:2390)
	at android.gov.nist.javax.sip.SipStackImpl.deleteListeningPoint(SipStackImpl.java:1592)
	at org.mobicents.restcomm.android.sipua.impl.SipManager.initialize(SipManager.java:131)
	at org.mobicents.restcomm.android.sipua.impl.SipManager.Register(SipManager.java:313)
	at org.mobicents.restcomm.android.sipua.impl.DeviceImpl.Register(DeviceImpl.java:209)
	at org.mobicents.restcomm.android.client.sdk.RCDevice.updateParams(RCDevice.java:416)
	at com.telestax.restcomm_messenger.MainActivity.onSharedPreferenceChanged(MainActivity.java:297)
	at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:475)
	at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:385)
	at android.preference.PreferenceManager.setNoCommit(PreferenceManager.java:535)
	at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:276)
	at android.preference.PreferenceActivity.addPreferencesFromResource(PreferenceActivity.java:1472)
	at com.telestax.restcomm_messenger.SettingsActivity.onCreate(SettingsActivity.java:15)
	at android.app.Activity.performCreate(Activity.java:5231)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
	... 11 more

**Comment by atsakiridis** [comment]
Can't reproduce it and the area where it happens has undergone some corrections so I think it is fixed
