### ISSUE TITLE
NPE: Attempt to invoke virtual method 'android.gov.nist.javax.sip.header.RequestLine

### ISSUE THREAD

**Issue by atsakiridis** [Mobicents/restcomm-android-sdk#168]
This was reported with: Messenger 1.0.0-BETA2#7

java.lang.NullPointerException: Attempt to invoke virtual method 'android.gov.nist.javax.sip.header.RequestLine android.gov.nist.javax.sip.message.SIPRequest.getRequestLine()' on a null object reference
	at android.gov.nist.javax.sip.stack.DefaultRouter.getNextHop(DefaultRouter.java:166)
	at android.gov.nist.javax.sip.stack.SIPTransactionStack.getNextHop(SIPTransactionStack.java:2254)
	at android.gov.nist.javax.sip.SipProviderImpl.getNewClientTransaction(SipProviderImpl.java:447)
	at org.mobicents.restcomm.android.sipua.impl.SipManager$6.run(SipManager.java:429)

**Comment by atsakiridis** [comment]
After observing the scenario, it's because the user uses as sip URI a bare number, for exaple '123456'

So this is a problem of not having validation facilities in the provided numbers. I'll open a separate issue for that to be more clear
