### ISSUE TITLE
Fix crash during Mute

### ISSUE THREAD

**Issue by atsakiridis** [Mobicents/restcomm-android-sdk#176]
This crash came up in @deruelle session when muting the call which in the bridge. Here's the stack trace from TestFairy:

FATAL EXCEPTION: main
Process: com.telestax.restcomm_messenger, PID: 20922
java.lang.NullPointerException: Attempt to invoke virtual method 'void org.mobicents.restcomm.android.client.sdk.AppRTCAudioManager.setMute(boolean)' on a null object reference
at org.mobicents.restcomm.android.client.sdk.RCConnection.setMuted(RCConnection.java:342)
at com.telestax.restcomm_messenger.CallActivity.onCheckedChanged(CallActivity.java:324)
at android.widget.CompoundButton.setChecked(CompoundButton.java:154)
at android.widget.CompoundButton.toggle(CompoundButton.java:113)
at android.widget.CompoundButton.performClick(CompoundButton.java:118)
at android.view.View$PerformClick.run(View.java:19873)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5289)
at java.lang.reflect.Method.invoke(Native Method)

**Comment by atsakiridis** [comment]
Seems like the that Mute isn't the route cause but a symptom. Logs suggest that at some point in the call webrtc STUN pings started timing out and connection was lost:

02:38 I/libjingle: Jingle:Conn[0xaea93a00:audio:l02KB7dn:1:0:local:udp:192.168.0.13:50874->6pXK/f9C:1:1694498815:stun:udp:23.23.228.238:64670|CRWI|7277816997780274687|-]: Unwritable after 5 ping failures and 5294 ms without a response, ms since last received ping=365666130 ms since last received data=4 rtt=3000
02:38 I/libjingle: Jingle:Conn[0xaea93a00:audio:l02KB7dn:1:0:local:udp:192.168.0.13:50874->6pXK/f9C:1:1694498815:stun:udp:23.23.228.238:64670|CRwI|7277816997780274687|-]: Sent STUN ping, id=6a5a7236472b52416e4d7738, use_candidate=0
02:38 D/PCRTCClient: IceConnectionState: DISCONNECTED

Then, right after media facilities were destroyed @deruelle hit mute, right before he would get navigated back to main screen. And since there was no check whether media facilities still exist, we got the NPE
