### ISSUE TITLE
Alert window leaked in Call screen

### ISSUE THREAD

**Issue by atsakiridis** [Mobicents/restcomm-android-sdk#180]
Seems that reachabilityState is lost somehow for RCConnection and when we hit disconnect an error message is popped. Steps to reproduce:

- Open Messenger with wifi
- Hit back to destroy Main Activity
- Close wifi
- Open Messenger
- Enable wifi
- Make call to 1235@Restcomm
- Hangup call before announcement is over (you will notice the Alert flashing in Call screen right before it is closed)

09-08 13:38:32.892    8325-8325/com.telestax.restcomm_messenger E/WindowManager﹕ android.view.WindowLeaked: Activity com.telestax.restcomm_messenger.CallActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{4294eef8 V.E..... R.....I. 0,0-1026,584} that was originally added here
            at android.view.ViewRootImpl.<init>(ViewRootImpl.java:346)
            at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
            at android.app.Dialog.show(Dialog.java:286)
            at com.telestax.restcomm_messenger.CallActivity.showOkAlert(CallActivity.java:395)
            at com.telestax.restcomm_messenger.CallActivity.onDisconnected(CallActivity.java:315)
            at org.mobicents.restcomm.android.client.sdk.RCConnection.haveConnectivity(RCConnection.java:504)
            at org.mobicents.restcomm.android.client.sdk.RCConnection.disconnect(RCConnection.java:319)
            at com.telestax.restcomm_messenger.CallActivity.onClick(CallActivity.java:219)
            at android.view.View.performClick(View.java:4445)
            at android.view.View$PerformClick.run(View.java:18446)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5146)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by atsakiridis** [comment]
Found the issue. Apparently we failed to unregister RCDevice broadcast receiver from Android and just re-registered a second time after RCClient shutdown. As a result reachability events were delivered to the old RCDevice instance instead of the current and reachability state was lost
