### ISSUE TITLE
Crash from TestFairy

### ISSUE THREAD

**Issue by atsakiridis** [Mobicents/restcomm-android-sdk#189]
Here's the session:

https://free.testfairy.com/projects/886758-restcommmessenger/builds/1719184/sessions/15

And the stack trace:

java.lang.NullPointerException: Attempt to invoke virtual method 'android.gov.nist.javax.sip.header.RequestLine android.gov.nist.javax.sip.message.SIPRequest.getRequestLine()' on a null object reference
	at android.gov.nist.javax.sip.stack.DefaultRouter.getNextHop(DefaultRouter.java:166)
	at android.gov.nist.javax.sip.stack.SIPTransactionStack.getNextHop(SIPTransactionStack.java:2254)
	at android.gov.nist.javax.sip.SipProviderImpl.getNewClientTransaction(SipProviderImpl.java:447)
	at org.mobicents.restcomm.android.sipua.impl.SipManager$6.run(SipManager.java:473)

**Comment by atsakiridis** [comment]
Same as #192
