### ISSUE TITLE
Fix NPE on JAIN SIP at getNewClientTransaction()

### ISSUE THREAD

**Issue by atsakiridis** [Mobicents/restcomm-android-sdk#192]
java.lang.NullPointerException
	at android.gov.nist.javax.sip.stack.DefaultRouter.getNextHop(DefaultRouter.java:166)
	at android.gov.nist.javax.sip.stack.SIPTransactionStack.getNextHop(SIPTransactionStack.java:2254)
	at android.gov.nist.javax.sip.SipProviderImpl.getNewClientTransaction(SipProviderImpl.java:447)
	at org.mobicents.restcomm.android.sipua.impl.SipManager$6.run(SipManager.java:473)

Checkout Test Fairy sessions 30-32:

https://free.testfairy.com/projects/886758-restcommmessenger/builds/1719184/sessions/32

Also seen this which seems the same:

java.lang.NullPointerException: Attempt to invoke virtual method 'android.gov.nist.javax.sip.header.RequestLine android.gov.nist.javax.sip.message.SIPRequest.getRequestLine()' on a null object reference
	at android.gov.nist.javax.sip.stack.DefaultRouter.getNextHop(DefaultRouter.java:166)
	at android.gov.nist.javax.sip.stack.SIPTransactionStack.getNextHop(SIPTransactionStack.java:2254)
	at android.gov.nist.javax.sip.SipProviderImpl.getNewClientTransaction(SipProviderImpl.java:447)
	at org.mobicents.restcomm.android.sipua.impl.SipManager$6.run(SipManager.java:473)

**Comment by atsakiridis** [comment]
Apart from the crash, I also see this section in android logcat, seems that settings are wrong:
- remote ip is 54.87.118.89:5080
- port is 8080

00:02:05 I/System.out: Setting remotePort:8080
00:02:05 I/System.out: Setting remoteIp:54.87.118.89:5080
00:02:05 V/SipManager: shutdown
00:02:05 V/SipManager: shutdown while stack is started
00:02:05 V/DeviceImpl: Register
00:02:05 I/SipManager: Registrar changed, reinitializing stack
00:02:05 I/System.out: Setting sipUserName:guest2
00:02:05 I/System.out: Setting sipPassword:1234
00:02:07 V/SipManager: initialize()
00:02:07 W/System.err: java.text.ParseException: sip:54.87.118.89:5080:8080 Illegal character in hostname:. (at offset 6)
00:02:07 W/System.err: 	at android.gov.nist.javax.sip.parser.URLParser.uriReference(URLParser.java:347)
00:02:07 W/System.err: 	at android.gov.nist.core.HostNameParser.hostPort(HostNameParser.java:307)
00:02:07 W/System.err: 	at android.gov.nist.javax.sip.parser.AddressParser.address(AddressParser.java:116)
00:02:07 W/System.err: 	at android.gov.nist.javax.sip.parser.URLParser.sipURL(URLParser.java:644)
00:02:07 W/System.err: 	at com.telestax.restcomm_messenger.MainActivity.onSharedPreferenceChanged(MainActivity.java:298)
00:02:07 W/System.err: 	at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:475)
00:02:07 W/System.err: 	at android.gov.nist.javax.sip.address.AddressFactoryImpl.createAddress(AddressFactoryImpl.java:124)
00:02:07 W/System.err: 	at org.mobicents.restcomm.android.client.sdk.RCDevice.updateParams(RCDevice.java:472)
00:02:07 W/System.err: 	at org.mobicents.restcomm.android.sipua.impl.DeviceImpl.Register(DeviceImpl.java:242)
00:02:07 W/System.err: 	at org.mobicents.restcomm.android.sipua.impl.SipManager.Register(SipManager.java:374)
00:02:07 W/System.err: 	at android.gov.nist.javax.sip.parser.StringMsgParser.parseAddress(StringMsgParser.java:319)
00:02:07 W/System.err: 	at org.mobicents.restcomm.android.sipua.impl.sipmessages.Register.MakeRequest(Register.java:47)
00:02:07 W/System.err: 	at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:385)
00:02:07 W/System.err: 	at android.preference.EditTextPreference.onDialogClosed(EditTextPreference.java:142)
00:02:07 W/System.err: 	at android.preference.Preference.tryCommit(Preference.java:1372)
00:02:07 W/System.err: 	at android.preference.EditTextPreference.setText(EditTextPreference.java:88)
00:02:07 W/System.err: 	at android.preference.Preference.persistString(Preference.java:1405)
00:02:07 W/System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
00:02:07 W/System.err: 	at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1238)
00:02:07 W/System.err: 	at android.preference.DialogPreference.onDismiss(DialogPreference.java:383)
00:02:07 W/System.err: 	at android.os.Looper.loop(Looper.java:136)
00:02:07 W/System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
00:02:07 W/System.err: 	at java.lang.reflect.Method.invoke(Method.java:515)
00:02:07 W/System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5001)
00:02:07 W/System.err: 	at dalvik.system.NativeStart.main(Native Method)
00:02:07 W/System.err: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
00:02:07 W/System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
00:02:07 W/System.err: 	at java.lang.reflect.Method.invokeNative(Native Method)

**Comment by atsakiridis** [comment]
And from another TF session I also see this:

00:04:31 W/System.err: java.text.ParseException: the scheme +1311@54.87.118.89 from the following uri +1311@54.87.118.89:8080 doesn't match ALPHA *(ALPHA / DIGIT / "+" / "-" / "." ) from RFC3261 (at offset 0) (at offset 0)
00:04:31 W/System.err: 	at android.gov.nist.javax.sip.address.AddressFactoryImpl.createURI(AddressFactoryImpl.java:233)
00:04:31 W/System.err: 	at org.mobicents.restcomm.android.sipua.impl.sipmessages.Message.MakeRequest(Message.java:35)
00:04:31 W/System.err: 	at org.mobicents.restcomm.android.sipua.impl.DeviceImpl.SendMessage(DeviceImpl.java:225)
00:04:31 W/System.err: 	at org.mobicents.restcomm.android.sipua.impl.SipManager.SendMessage(SipManager.java:493)
00:04:31 W/System.err: 	at com.telestax.restcomm_messenger.MessageActivity.onClick(MessageActivity.java:111)
00:04:31 W/System.err: 	at org.mobicents.restcomm.android.client.sdk.RCDevice.sendMessage(RCDevice.java:349)
00:04:31 W/System.err: 	at android.os.Looper.loop(Looper.java:136)
00:04:31 W/System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
00:04:31 W/System.err: 	at android.view.View$PerformClick.run(View.java:18422)
00:04:31 W/System.err: 	at android.os.Handler.handleCallback(Handler.java:733)
00:04:31 W/System.err: 	at android.view.View.performClick(View.java:4438)
00:04:31 W/System.err: 	at java.lang.reflect.Method.invokeNative(Native Method)
00:04:31 W/System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5001)
00:04:31 W/System.err: 	at dalvik.system.NativeStart.main(Native Method)
00:04:31 W/System.err: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
00:04:31 W/System.err: 	at java.lang.reflect.Method.invoke(Method.java:515)
00:04:31 W/System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
00:04:31 W/System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)

**Comment by atsakiridis** [comment]
Seems all above issues are triggered by bad SIP URIs used either on the call uri or on the register URI being constructed from the settings. I guess best fix is to do proper validation. TF sessions:

https://free.testfairy.com/projects/886758-restcommmessenger/builds/1719184/sessions/32
https://free.testfairy.com/projects/886758-restcommmessenger/builds/1719184/sessions/31
https://free.testfairy.com/projects/886758-restcommmessenger/builds/1719184/sessions/30
https://free.testfairy.com/projects/886758-restcommmessenger/builds/1719184/sessions/15

For the call SIP uri things are pretty straigt forward. For the settings I'd say not allow a port in the IP string cause this is what is causing the issue: instead of ip string xx.xx.xx.xx:5080 is used and then for the port a separate 8080 is used which is wrong

**Comment by atsakiridis** [comment]
Addressed at #164 and #169
