### ISSUE TITLE
Fix crash on 'Attempt to invoke virtual method ... LinkedList.iterator()' on a null object reference

### ISSUE THREAD

**Issue by atsakiridis** [Mobicents/restcomm-android-sdk#193]
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in org.mobicents.restcomm.android.client.sdk.RCDevice@a52c520
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:891)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator java.util.LinkedList.iterator()' on a null object reference
	at android.gov.nist.javax.sip.stack.UDPMessageProcessor.stop(UDPMessageProcessor.java:270)
	at android.gov.nist.javax.sip.SipProviderImpl.removeListeningPoints(SipProviderImpl.java:1082)
	at android.gov.nist.javax.sip.SipStackImpl.deleteSipProvider(SipStackImpl.java:1619)
	at org.mobicents.restcomm.android.sipua.impl.SipManager.unbind(SipManager.java:176)
	at org.mobicents.restcomm.android.sipua.impl.DeviceImpl.unbind(DeviceImpl.java:78)
	at org.mobicents.restcomm.android.client.sdk.RCDevice.onReachabilityChanged(RCDevice.java:180)
	at org.mobicents.restcomm.android.client.sdk.RCDevice.onReceive(RCDevice.java:159)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:881)
	... 7 more

**Comment by atsakiridis** [comment]
Some notes:
- There is no android logcat at the time of the crash; TF has stopped recording at 10 minutes and crash occurred at about an hour
- Seems like app got a reachability update that networking got disabled and hence tried to unbind the networking facilities
- App seems to be on backgrounded at the time of the crash, so maybe android decided to do something about the app 

Been unable to reproduce this with various tests:
- Tried unbinding twice and see if it is handled gracefully and seems that it is
- Tried various scenarios of reachability updates both when the app is in the foreground as well as when the app is in the background

What I plan to do is allow of longer TF sessions in hopes of issue getting reproduced again and this time having more data to work with.

**Comment by atsakiridis** [comment]
Haven't seen this issue for more than a month. Let's close for now and keep an eye on TF sessions in case it comes up in the future. Could be fixed indirectly in the meantime
