### ISSUE TITLE
First time Messenger ever comes up Registration fails

### ISSUE THREAD

**Issue by atsakiridis** [Mobicents/restcomm-android-sdk#59]
Reason is:

java.text.ParseException: sip:bob@: Missing host name (at offset 8)
06-30 18:41:13.965    3232-3232/com.telestax.restcomm_messenger W/System.err﹕ at android.gov.nist.core.HostNameParser.host(HostNameParser.java:193)
06-30 18:41:13.965    3232-3232/com.telestax.restcomm_messenger W/System.err﹕ at android.gov.nist.core.HostNameParser.hostPort(HostNameParser.java:266)
06-30 18:41:13.965    3232-3232/com.telestax.restcomm_messenger W/System.err﹕ at android.gov.nist.javax.sip.parser.URLParser.sipURL(URLParser.java:644)
06-30 18:41:13.965    3232-3232/com.telestax.restcomm_messenger W/System.err﹕ at android.gov.nist.javax.sip.parser.URLParser.uriReference(URLParser.java:347)
06-30 18:41:13.965    3232-3232/com.telestax.restcomm_messenger W/System.err﹕ at android.gov.nist.javax.sip.parser.AddressParser.address(AddressParser.java:116)
06-30 18:41:13.965    3232-3232/com.telestax.restcomm_messenger W/System.err﹕ at android.gov.nist.javax.sip.parser.StringMsgParser.parseAddress(StringMsgParser.java:319)
06-30 18:41:13.965    3232-3232/com.telestax.restcomm_messenger W/System.err﹕ at android.gov.nist.javax.sip.address.AddressFactoryImpl.createAddress(AddressFactoryImpl.java:124)
06-30 18:41:13.965    3232-3232/com.telestax.restcomm_messenger W/System.err﹕ at org.mobicents.restcomm.android.sipua.impl.sipmessages.Register.MakeRequest(Register.java:30)
06-30 18:41:13.965    3232-3232/com.telestax.restcomm_messenger W/System.err﹕ at org.mobicents.restcomm.android.sipua.impl.SipManager.Register(SipManager.java:284)
06-30 18:41:13.965    3232-3232/com.telestax.restcomm_messenger W/System.err﹕ at org.mobicents.restcomm.android.sipua.impl.DeviceImpl.Register(DeviceImpl.java:164)
06-30 18:41:13.965    3232-3232/com.telestax.restcomm_messenger W/System.err﹕ at org.mobicents.restcomm.android.client.sdk.RCDevice.updateParams(RCDevice.java:344)
06-30 18:41:13.965    3232-3232/com.telestax.restcomm_messenger W/System.err﹕ at com.telestax.restcomm_messenger.MainActivity.onClick(MainActivity.java:158)
06-30 18:41:13.965    3232-3232/com.telestax.restcomm_messenger W/System.err﹕ at android.view.View.performClick(View.java:4445)
06-30 18:41:13.965    3232-3232/com.telestax.restcomm_messenger W/System.err﹕ at android.view.View$PerformClick.run(View.java:18446)
06-30 18:41:13.965    3232-3232/com.telestax.restcomm_messenger W/System.err﹕ at android.os.Handler.handleCallback(Handler.java:733)
06-30 18:41:13.965    3232-3232/com.telestax.restcomm_messenger W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:95)
06-30 18:41:13.965    3232-3232/com.telestax.restcomm_messenger W/System.err﹕ at android.os.Looper.loop(Looper.java:136)
06-30 18:41:13.965    3232-3232/com.telestax.restcomm_messenger W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5146)
06-30 18:41:13.965    3232-3232/com.telestax.restcomm_messenger W/System.err﹕ at java.lang.reflect.Method.invokeNative(Native Method)
06-30 18:41:13.965    3232-3232/com.telestax.restcomm_messenger W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:515)
06-30 18:41:13.965    3232-3232/com.telestax.restcomm_messenger W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
06-30 18:41:13.965    3232-3232/com.telestax.restcomm_messenger W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
06-30 18:41:13.965    3232-3232/com.telestax.restcomm_messenger W/System.err﹕ at dalvik.system.NativeStart.main(Native Method)

Apparently, once we navigate to the Settings everything is fixed and then stored in SharedPreferences which is why it never occurs again.

**Comment by atsakiridis** [comment]
This happens for calls as well and anything related to JAIN SIP
